### ISSUE TITLE
todo newsletter

### ISSUE THREAD

**Issue by Fil** [Fil/rezo-squelettes#4]
- [ ] Créer 1 nouvelle liste (portail@rezo.net) (?)
- [ ] subject: “La semaine des copines et des copains” / des copaines
- [ ] Infos d'entête / pied
- [ ] afficher contenu des posts (?)
- [ ] icône de type (audio/vidéo) (?)
- [ ] afficher les brèves en bas (?)
- [ ] afficher les liens son (?)
